<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Ruby on Mike Perham</title>
    <link>https://www.mikeperham.com/tags/ruby/</link>
    <description>Recent content in Ruby on Mike Perham</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Wed, 27 Jan 2010 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://www.mikeperham.com/tags/ruby/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Scalable Ruby Processing with EventMachine</title>
      <link>https://www.mikeperham.com/2010/01/27/scalable-ruby-processing-with-eventmachine/</link>
      <pubDate>Wed, 27 Jan 2010 00:00:00 +0000</pubDate>
      
      <guid>https://www.mikeperham.com/2010/01/27/scalable-ruby-processing-with-eventmachine/</guid>
      <description>I gave a talk at Austin On Rails last night on using EventMachine, focused on maximizing concurrency when processing a message queue. There were a lot of questions, mostly revolving around the flow of execution within EventMachine code. To this point, there were two common stumbling points people seemed to have:
Ruby developers are not used to treating blocks as true callbacks where they are executing at some point in the future.</description>
    </item>
    
    <item>
      <title>Ruby Scoping Oddity</title>
      <link>https://www.mikeperham.com/2008/05/22/ruby-scoping-oddity/</link>
      <pubDate>Thu, 22 May 2008 00:00:00 +0000</pubDate>
      
      <guid>https://www.mikeperham.com/2008/05/22/ruby-scoping-oddity/</guid>
      <description>This prints out &amp;ldquo;1&amp;rdquo;:
`
begin a = 1 raise RuntimeError, &#34;foo&#34; rescue =&gt; e puts a end ` I would think that a would be out of scope inside the rescue section but I guess Ruby considers the rescue section part of the begin/end block?</description>
    </item>
    
  </channel>
</rss>
